int8    POSITION_UNKNOWN    = 0
    # 主车道线
int8    EGO_LEFT            = -1
int8    EGO_RIGHT           = 1
    # 临近车道线
int8    ADJACENT_LEFT       = -2
int8    ADJACENT_RIGHT      = 2
    # 第三临近车道线
int8    THIRD_LEFT          = -3
int8    THIRD_RIGHT         = 3
    # 第四临近车道线
int8    FOURTH_LEFT         = -4
int8    FOURTH_RIGHT        = 4
    # 路沿
int8    CURB_LEFT           = -5
int8    CURB_RIGHT          = 5


int8    laneline_position