uint8    LANELINETYPE_UNKNOWN                            = 0
    # 单实线      ^          [ANP提供]
uint8    LANELINETYPE_SINGLE_SOLID_LINE                  = 1
    # 单虚线                [ANP提供]
uint8    LANELINETYPE_SINGLE_DASHED_LINE                 = 2
    # 双实线                [ANP提供]
uint8    LANELINETYPE_DOUBLE_SOLID_LINE                  = 3
    # 双虚线                [ANP提供]
uint8    LANELINETYPE_DOUBLE_DASHED_LINE                 = 4
    # 左虚右实              [ANP提供]
uint8    LANELINETYPE_LEFT_DASHED_LINE_RIGHT_SOLID_LINE  = 5
    # 左实右虚              [ANP提供]
uint8    LANELINETYPE_LEFT_SOLID_LINE_RIGHT_DASHED_LINE  = 6
    # 双黄双白实线          [ANP提供]
uint8    LANELINETYPE_DOUBLE_WHITE_DOUBLE_YELLOW_SOLID   = 7
    # 双黄双白虚线          [ANP提供]
uint8    LANELINETYPE_DOUBLE_WHITE_DOUBLE_YELLOW_DASHED  = 8
    # 路沿                  [ANP提供]
uint8    LANELINETYPE_CURB_LINE                          = 9

uint8    laneline_type