uint8    SV_NONE                 = 0
uint8    SV_POLICE_VEHICLE       = 1        # 警车                  #cam提供    lidar 不提供
uint8    SV_POLICE_MOTORCYCLE    = 2        # 警用摩托车             #cam提供    lidar 不提供
uint8    SV_FIRE_ENGINE          = 3        # 消防车                #cam提供    lidar 不提供
uint8    SV_AMBULANCE            = 4        # 救护车                #cam提供    lidar 不提供
uint8    SV_ENGINEERING_VEHICLE  = 5        # 施工工程车             #cam提供    lidar 提供
uint8    SV_SCHOOL_BUS           = 6        # 校车                  #cam提供    lidar 不提供
uint8    SV_BUS                  = 7        # 公交车                #cam提供    lidar 不提供
uint8    SV_SPRINKLER            = 8         # 洒水车                #cam提供    lidar 不提供

uint8    svtype