
uint8    OBJECT_TYPE_UNKNOWN             = 0
uint8    OBJECT_TYPE_UNKNOWN_MOVABLE     = 1
uint8    OBJECT_TYPE_UNKNOWN_UNMOVABLE   = 2
uint8    PEDESTRIAN                      = 3  # cam提供 lidar 提供
uint8    BICYCLE                         = 4  # cam提供 lidar 提供
uint8    VEHICLE                         = 5  # cam提供 lidar 提供
uint8    BARRIER                         = 6   # cam提供 lidar 提供


uint8    type