float64 longitude 0         # 经度，rad
float64 latitude 0          # 纬度，rad
float64 altitude 0          # 海波高度，m
float64 roll 0              # 自车横滚角，rad，ENU
float64 pitch 0             # 自车俯仰角
float64 yaw   0             # 自车偏航角
float64 vel_x 0             # ENU坐标系的速度分量
float64 vel_y 0
float64 vel_z 0
float64 mercator_x 0        # utm m
float64 mercator_y 0        # utm m
float64 mercator_z 0        # utm m
