# c0 coefficient which is Lane_Position. Positive to the left. 
float64 c0  

# c1 coefficient which Heading Angle can be calculated from 
float64 c1 

# c2 coefficient which Lane Curvature can be calculated from. Positive if curved to left. 
float64 c2 

# c3 coefficient which Lane Curvature Derivative can be calculated from. Sign is According to Curvature. 
float64 c3  

# 纵向起始点, 靠近host vehicle 
float64 start  

# 纵向终止点, 远离host vehicle 
float64 end  