bool on_use
float64 range
float64 angle
float64 relative_radial_velocity 
float64 relative_tangential_velocity
float64 radial_velocity 
float64 tangential_velocity 
float64 life_time 

float64 vambig_radial_velocity

float64 vambig 
float64 vehicle_yaw_rate 
float64 rcs 
float64 longitude_dist 
float64 lateral_dist 
float64 obstacle_prob 
uint8 origin_id
uint8 mode 


RadarSegmentationType radar_seg_type 
RawMotionState raw_motion_state 
RadarRoiType radar_roi_type 