std_msgs/Header header

int32 container_counter

float64 lat_pos
float64 lat_pos_var
float64 long_pos
float64 long_pos_var
float64 lat_vel
float64 lat_vel_var
float64 long_vel
float64 long_vel_var
float64 lat_acc
float64 lat_acc_var
float64 long_acc
float64 long_acc_var
int32 obj_id
int32 track_status
float64 height
float64 exist_conf
int32 obj_dyn_class
int32 obj_class
float64 obstacle_probability
#new sw add front radar lifetime

#corner radar specific
float32 heading
float32 heading_var
float32 life_time
float32 obj_class_conf
float32 lat_ext_left
float32 lat_ext_var
float32 lat_ext_right
float32 lat_ext_right_var

float32 coast_index

float32 long_ext_back
float32 long_ext_back_var
float32 long_ext_front
float32 long_ext_front_var
float32 prioritisation



