uint8       OPEN_STATUS_OPEN                  = 0
uint8       OPEN_STATUS_CLOSE                 = 1
uint8       OPEN_STATUS_UNKNOWN               = 2

uint8       ACTIVE_STATUS_INACTIVE            = 0
uint8       ACTIVE_STATUS_ACTIVE              = 1
uint8       ACTIVE_STATUS_ACTIVE_UNKNOWN      = 2

uint8       back_trunk                                # 后备箱
uint8       back_trunk_id                             # 后备箱标志位
uint8       driver_seat                               # 驾驶员区域状态
uint8       driver_seat_id                            # 驾驶员区域标志位
uint8       left_front_door                           # 左前门状态
uint8       left_front_door_id                        # 左前门状态标志位
uint8       right_front_door                          # 右前门状态
float32     bat_soc_rpt                               # 获取电量
uint8       high_beam_status                          # 远光灯
uint8       high_beam_status_id                       # 远光灯标志位
uint8       hood                                      # 前机盖状态
uint8       hood_id                                   # 前机盖状态标志位
uint8       rear_left_door                            # 左后门状态
uint8       rear_left_door_id                         # 左后门状态标志位
uint8       rear_right_door                           # 右后门状态
uint8       rear_right_door_od                        # 右后门状态标志位
uint8       wipers_id                                 # 雨刮标志位
uint8       driver_belt                               # 驾驶员安全带状态
uint8       driver_belt_id                            # 驾驶员安全带状态标志位
uint8       wipers                                    # 雨刷
uint8       passenger_belt                            # 乘客安全带状态
uint8       passenger_belt_id                         # 乘客安全带状态标志位
uint8       front_foglight_status                     # 前雾灯状态
uint8       left_rearview_mirror                      # 左后视镜状态
uint8       left_rearview_mirror_id                   # 左后视镜状态标志位
uint8       left_turnlight_status                     # 左转向灯状态
uint8       parklight_onwarning                       # 制动灯
uint8       parktail_light_status                     # 后尾制动灯
uint8       passenger_bag                             # 乘客行李状态
uint8       passenger_bag_id                          # 乘客行李状态标志位
uint8       passenger_seat                            # 乘客检测状态
uint8       passenger_seat_id                         # 乘客检测状态标志位
uint8       rear_foglight_status                      # 后雾灯
uint8       reverse_gearswitch                        # 倒档开关
uint8       right_rearview_mirror                     # 右后视镜状态
uint8       right_rearview_mirror_id                  # 右后视镜状态标志位
uint8       right_turnlight_status                    # 右转向灯状态


