common_msgs/Header header

bool     hna_swt_fb                   #HNA功能开关状态
bool     lane_chg_swt_fb              #变道辅助开关反馈
bool     auto_lane_chg_cfm_fb         #自动变道确认开关反馈
uint8    auto_lane_chg_rmn_set_fb     #变道提醒开关反馈
uint8    auto_lane_chg_set_fb         #变道风格设置反馈
bool     hwa_study_mod_swt_fb         #HWA功能学习模式开关反馈
uint8    alc_fct_st                   #变道辅助功能状态显示
uint8    takeover_req                 #车辆接管请求
uint8    hwa_fct_rmn                  #HWA/HNA功能提醒
uint8    lane_chg_req                 #变道确认请求
bool     turn_lgt_cls_rmn             #转向灯关闭提醒
uint8    hwa_fct_lamp                 #HWA功能指示灯
uint8    lgtd_ctrl_spd_set_st         #纵向控制功能设置车速显示
uint8    lgtd_ctrl_tigap_set_st       #纵向功能时距设置时距显示
uint8    lgtd_ctrl_tar_disp           #纵向目标距离显示
uint8    acc_fctrmn                   #ACC功能提醒
uint8    acc_fct_lamp                 #ACC功能状态指示灯
uint8    his_estimd_veh_m            #HIS估算整车质量
