
common_msgs/Header header

uint8       brk_flt
uint8       gear_flt
float32     steer_flt
uint8       drvg_flt
uint8       veh_spd
uint8       mot_spd
uint16      mot_tq
float32     brk_pdl_posn
float32     brkdecel_resp
float32     accl_pdl_posn
float32     accl_pdl_posn_resp
int8        gear_curr_posn
int8        gear_cmd_resp
bool        brk_pdl_drvr_ovrd
bool        accl_pdl_drvr_ovrd
bool        gear_drvr_ovrd
bool        gear_shift_prmt_ena
bool        gear_shift_prmt_ena_vld
uint8       e_pb_st
bool        e_pb_st_vld
bool        veh_spd_vld
bool        mot_spd_vld
bool        mot_tq_vld
int8        gear_pos_disp
uint32      veh_max_drv_tq
int32       veh_maxrgn_tq
float32     veh_act_spd
bool        veh_act_spd_vld
uint8       veh_drvg_dir
uint8       adh_lvl
uint16      veh_m
uint16      tot_milg
uint8       hzrd_lgt_st
uint8       trlr_cnctn_st
uint16      rlsbri
bool        fr_trsm_shift_st
bool        re_trsm_shift_st



