uint8           type                                # 车道线类型
uint8           tracking_status                     # 跟踪状态
float64         dy                                  # Y向偏移量
float64         angle_yaw                           # 角度
float64         curvature                           # 曲率
float64         curvature_change                    # 曲率变化
uint8           quality                             # 质量
uint32          tracking_id                         # 跟踪ID
float64         start_point_dx                      # 起始点Dx
float64         end_point_dx                        # 终止点Dx
float64         front_cross_point_dx                # 前方交叉点Dx
float64         front_cross_point_dy                # 前方交叉点Dy
float32         tracking_time                       # 跟踪时间

