
common_msgs/Header header

float32    fr_left_tire_posn
float32    fr_right_tire_posn
float32    re_left_tire_posn
float32    re_right_tire_posn
uint8    fr_left_whl_dir
uint8    fr_right_whl_dir
uint8    re_left_whl_dir
uint8    rere_right_whl_dir
float32    fr_left_whl_spd
uint8    fr_left_whl_cntr
float32    fr_right_whl_spd
uint8    fr_right_whl_cntr
float32    re_right_whl_spd
uint8    re_right_whl_cntr
float32    re_left_whl_spd
uint8    re_left_whl_cntr
bool    fr_left_whl_spd_vld
bool    fr_right_whl_spd_vld
bool    re_left_whl_spd_vld
bool    re_right_whl_spd_vld



